# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        stages: [commit, manual]
      - id: end-of-file-fixer
        stages: [commit, manual]
      - id: check-yaml
        stages: [commit, manual]
      - id: check-added-large-files
        stages: [commit, manual]
      - id: check-executables-have-shebangs
        stages: [commit, manual]
      - id: check-json
        stages: [commit, manual]
      - id: check-shebang-scripts-are-executable
        stages: [commit, manual]
      - id: check-symlinks
        stages: [commit, manual]
      - id: detect-private-key
        stages: [commit, manual]
      - id: mixed-line-ending
        stages: [commit, manual]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
